### ISSUE TITLE
How can I use your library like the picture?

### ISSUE THREAD

**Issue by BigheadIan** [KIDLY/KIDLY#1]
Hi, I'm a new user of "KIDLY"
In your demo sample I found that, you can change the background of series.
I can't find out how can I do that.
Please give me a big hand.
Here is the picture of your demo.
![2012-12-19_221155](https://f.cloud.github.com/assets/1811293/22036/7d13d9f4-49e6-11e2-9b35-c237b310e0ea.png)

**Comment by DotHst** [comment]
Hi, use JFreeChart's method in this way.
JFreeChart.getCategoryPlot().getRenderer().setSeriesPaint(X, Color.cyan); //X is your data index

And you can see some detail in the file. -> [Chart manual](https://docs.google.com/spreadsheet/ccc?key=0AuI3RQw4hoKddFJSbGh6UFF0RnlCM2JOYko3N2lva3c)
